name: "build and test"

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.razor'

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.100-rc.2.24474.11
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
